version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    command: --init-file /tmp/init.sql
    volumes:
      - /var/lib/mysql
      - ./init.sql:/tmp/init.sql
  api:
    restart: always
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/customer_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_APPLICATION_JSON : '{
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQLDialect"
      }'