spring:
  profiles:
    active: test
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: docker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://mysqldb:3306/customer_db
    username: root
    password: root
version: "Docker"
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: root
    password: root
version: "Test"
