spring:
  profiles:
    active: test
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: dev
version: "Dev"
---
spring:
  config:
    activate:
      on-profile: test
version: "Latest"
